"""add is_active to users

Revision ID: 817dbec35363
Revises: fc773b58aff4
Create Date: 2026-09-27 11:03:33.772332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817dbec35363'
down_revision: Union[str, Sequence[str], None] = 'fc773b58aff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.execute("UPDATE users SET is_active = TRUE")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
